#!/bin/sh
HOST='172.29.211.163'
USER='adp'
PASSWD='r4p1Dt03'

######################################
### hand create these directories and
### make them adp clients 777
### mkdir /adp/home/fsprint
### mkdir /adp/home/fsprint/crowe
### mkdir /adp/transmit
### mkdir /adp/3party/fs/fslaserforms/current
### mkdir /adp/home/unixnew
######################################
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd /adp/home/fsprint
cd /adp/home/fsprint
mget *
lcd /adp/home/fsprint/crowe
cd /adp/home/fsprint/crowe
mget *
quit
END_SCRIPT

ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd /adp/home/unixnew
cd /adp/home/unixnew
mget *
quit
END_SCRIPT

SOURCEREALBASE='/adp/masterdbases/reality1/H.qMUFbMACQb'
#TARGETREALBASE='/adp/masterdbases/reality1/H.IglshWsqbY'
TARGETREALBASE='/adp/masterdbases/reality1/H.CloxRdn5ufr'

ACCTNAME='LIBRARY'
FILENAME='OVERLAY-TABLE'
rm $TARGETREALBASE/$ACCTNAME/,$FILENAME
rm $TARGETREALBASE/$ACCTNAME/$FILENAME
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
get ,$FILENAME
get $FILENAME
quit
END_SCRIPT

ACCTNAME='QS-=5BGM=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BLR=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BMB=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BMBCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BLAM=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BJAG=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BNIS=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BNISCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BMAZDA=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BMAZDACAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BMIT=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BMITCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BKIA=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BKIACAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BLEX=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BLEXCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BISUZU=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BINFIN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BINFINCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BHONDA=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BHONDPCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BHONDACAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BGMCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BFORD=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BFIAT=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BHYUCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BHYU=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BFERRARI=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BCHRY=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BCHRYCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BBMWMC=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BBEN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BBENCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BACURACAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BAUDICAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BAUDI=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-FISKER'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-HONDAMC'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-IND'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-LEASE'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-MACK'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-MASER'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-MCLAR'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-PACCAR'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-REC'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-SELTRK'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-STD'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-SUZCAN'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-TRK'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BDTNA=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BACURA=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BVW=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BVWCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BBMW=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BVOLVO=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BTOY=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BTOYCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BSUZ=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BSUB=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BSUBCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BPORSCHE=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BPORCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BSPRINT=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='QS-=5BNSTAR=5D'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT



################################################################
################################################################
################################################################

ACCTNAME='FSTOOLS-PL'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='DEB-PL'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='NEAL-PL'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='DIANE'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='RICK'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='PETE'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='BARB'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='FS.PUBS'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='DEBTEST'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

ACCTNAME='MARE'
rm $TARGETREALBASE/$ACCTNAME/*
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
binary
prompt
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
quit
END_SCRIPT

exit 0





