#!/bin/sh
HOST='c04incdmsd75.drive.connectcdk.com'
USER='adp'
PASSWD='8atEryl0'

SOURCEREALBASE='/adp/masterdbases/reality1/H.Um3hWSnSlyGy'
TARGETREALBASE='/adp/masterdbases/reality1/H.vc2YYl2J8'

ACCTNAME='RACHEL'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BGENESIS=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='BARB'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BRR=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BGM=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BLR=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BMB=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BMBCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BLAM=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BJAG=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BNIS=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BNISCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BMAZDA=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BMAZDACAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BMIT=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BMITCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BKIA=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BKIACAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BLEX=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BLEXCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BISUZU=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BINFIN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BINFINCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BHONDA=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BHONDPCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BHONDACAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BGMCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BFORD=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BFIAT=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BHYUCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BHYU=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BFERRARI=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BCHRY=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BCHRYCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BBMWMC=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BBEN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BBENCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BACURACAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BAUDICAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BAUDI=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-FISKER'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-HONDAMC'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-IND'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-LEASE'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-MACK'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-MASER'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-MCLAR'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-PACCAR'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-REC'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-SELTRK'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-STD'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-SUZCAN'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-TRK'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BDTNA=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BACURA=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BVW=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BVWCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BBMW=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BVOLVO=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BTOY=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BTOYCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BSUZ=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BSUB=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BSUBCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BPORSCHE=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BPORCAN=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BSPRINT=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='QS-=5BNSTAR=5D'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='FSTOOLS-PL'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='DEB-PL'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='NEAL-PL'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='DIANE'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='RICK'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='PETE'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='FS.PUBS'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='DEBTEST'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='MARE'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT

ACCTNAME='FSDEV'
rm $TARGETREALBASE/$ACCTNAME/*
lftp<<END_SCRIPT
open sftp://$HOST
user $USER $PASSWD
lcd $TARGETREALBASE/$ACCTNAME
cd $SOURCEREALBASE/$ACCTNAME
mget *
bye
END_SCRIPT


exit 0

